### ISSUE TITLE
Certain jewels not being filtered properly

### ISSUE THREAD

**Issue by reyals106** [Odgug/CC-Vault#4]
So for the most part it seems to work but when testing, these jewels will always fall through the filter.

Chipped
25 Size, 6% trap
27 Size, 557 dura
25 Size, +6.9 mining
32 Size 2.1% copious

I tested with the filters set to DENY not chipped and <=18 or all FILTER (ALL) only chipped and >18.  

(note >18 seems to still include Size 18 but that's not an issue I can't work around)

I've tested in a system as simple as a chest with these jewels over a smart hopper and they keep going through.

I'm sure there are other examples but it's 90% accurate in my filtering.  At least no good jewels are being recycled.

EDIT: Going through jewels when I have time looking for things that didn't get filtered properly.
Not Chipped Example

Flawed
25 Size, +7.4 Mining Speed, +0.24 Reach

Test with ALLOWS only flawed and >23  Filter set to Filter ALL

**Comment by Odgug** [comment]
You're in the wrong repo btw, this is the CC Vault repo not the vault filters repo but ill still try to help.
All those conditions are very difficult to understand by text, can you send a screenshot of the attribute filter's UI when ur hovering over the nametag icon so i can see the settings, as well as a screenshot of the jewel thats expected to go through but is not?

**Comment by reyals106** [comment]
I think you can ignore this for now, I'll let you know if I encounter it again but after going through this for a while, after coming back from breakfast, i hit F3+a to reload chunk and it filtered properly.  Which is strange since there hasn't been a server restart of anything.

Thanks though, I'll post in the correct repo in the future!
